### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by csicar** [Jomik/Valetudo-UI#1]
Hi, I'd like to help with implementing some functionality. 
I'd start with implementing the settings ui (basically copying all the options from the valetudo ui)

**Comment by Jomik** [comment]
Hey! Sweet!
I am still messing around, so the environment may be quite unstable.
I would love to get some development done on a settings page though!
That should be pretty straight forward too.
I am happy if you open a discussion here, enabled those now - or you can ping me on the Valetudo Telegram - if you have any questions, ideas, or whatever that I can help with there.

Quick overview..
We are using [material-ui](https://material-ui.com/), [react-router](https://github.com/ReactTraining/react-router) and [axios-hooks](https://github.com/simoneb/axios-hooks)

I am considering [react-query](https://react-query.tanstack.com/) instead of axios-hooks..

I have set up a [miragejs](https://github.com/miragejs/miragejs) server for mocking out API during development.
Alternatively, you can disable that and 
point towards your Valetudo clone with CORS enabled and use the MockRobot.
or build Valetudo with CORS enabled to talk to your own robot.

**Comment by Braintoe** [comment]
Hi there,
out of curiosity: do you plan to make this multi-language capable as e.g. the Valetudo RE fork is? If so, I would be happy to contribute localised german texts.

**Comment by Jomik** [comment]
> Hi there,
> out of curiosity: do you plan to make this multi-language capable as e.g. the Valetudo RE fork is? If so, I would be happy to contribute localised german texts.

Hey,  thank you! This project is meant to be merged into Valetudo as a replacement of the current client, thus I will have to take the same stance as written in https://valetudo.cloud/pages/dev_faq.html

**Comment by Jomik** [comment]
I am gonna close this issue, please open another issue or a discussion if needed 👍
